# Generated by Django 6.1.1 on 2026-09-29 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conduit", "0004_export"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditingLink",
            fields=[
                ("id", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("key_hash", models.CharField(max_length=64)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editing_link",
                        to="conduit.article",
                    ),
                ),
            ],
        ),
    ]
