logger:
  enable: true
  level: info
  format: json
server:
  port: <%= get_env(name="PORT") %>
  binding: 0.0.0.0
  host: http://localhost
  middlewares:
    secure_headers:
      enable: true
workers:
  mode: BackgroundQueue
queue:
  kind: Postgres
  uri: <%= get_env(name="DATABASE_URL") %>
  reaper:
    age_minutes: 1
    interval_seconds: 30
database:
  uri: <%= get_env(name="DATABASE_URL") %>
  enable_logging: false
  connect_timeout: 5000
  idle_timeout: 600000
  min_connections: 1
  max_connections: 10
auth:
  jwt:
    secret: <%= get_env(name="SECRET_KEY_BASE") %>
    expiration: 604800
