logger:
  enable: true
  level: info
  format: json
server:
  port: <%= get_env(name="PORT", default="4103") %>
  binding: 0.0.0.0
  host: <%= get_env(name="HOST") %>
workers:
  mode: BackgroundAsync
database:
  uri: <%= get_env(name="DATABASE_URL") %>
  enable_logging: false
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 1
  max_connections: 10
auth:
  jwt:
    secret: <%= get_env(name="JWT_SECRET") %>
    expiration: 604800
