//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::articles::Entity as Articles;
pub use super::comments::Entity as Comments;
pub use super::favorites::Entity as Favorites;
pub use super::follows::Entity as Follows;
pub use super::users::Entity as Users;
