logger:
  enable: true
  level: info
  format: compact
server:
  port: <%= get_env(name="PORT", default="4103") %>
  host: http://localhost
  middlewares:
    secure_headers:
      enable: true
workers:
  mode: BackgroundAsync
database:
  uri: <%= get_env(name="DATABASE_URL", default="postgres://loco:loco@localhost:54329/conduit") %>
  enable_logging: false
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 1
  max_connections: 10
  auto_migrate: true
auth:
  jwt:
    secret: <%= get_env(name="JWT_SECRET", default="LRKkNeVr4liTgqOglDoA") %>
    expiration: 604800
