source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg"
gem "puma"
gem "bootsnap", require: false
gem "bcrypt"
gem "jwt"
gem "jbuilder"
gem "rack-cors"

group :development, :test do
  gem "rubocop-rails-omakase", require: false
end
