# Generated by Django 6.1.1 on 2026-09-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conduit", "0002_article_published_at_article_revision_article_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("failures", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
    ]
