source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg"
gem "puma"
gem "bootsnap", require: false
gem "bcrypt"
gem "jwt"
gem "jbuilder"
gem "rack-cors"
gem "solid_queue", "~> 1.7"
gem "faye-websocket", "~> 0.12"

group :development, :test do
  gem "rubocop-rails-omakase", require: false
end
