FROM ruby:3.3.2-slim
WORKDIR /work/app
ENV BUNDLE_PATH=/usr/local/bundle RAILS_ENV=development
RUN apt-get update -qq && apt-get install --no-install-recommends -y \
    build-essential libpq-dev git ca-certificates curl && \
    rm -rf /var/lib/apt/lists/*
RUN gem install bundler -v 2.5.23 --no-document
COPY scaffold/Gemfile scaffold/Gemfile.lock ./
RUN bundle install
CMD ["bash"]
